name: Push to GCR and Deploy GitHub Action
on:
  push
jobs:
  build-and-push-to-gcr-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
      
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: hidden-solstice-337107
          image_name: myimage
          image_tag: latest
          dockerfile: Dockerfile
       - name: Deploy
         run: |
           gcloud run deploy myimage --image gcr.io/hidden-solstice-337107/myimage@sha256:a02760978ee28b0231e4e44833dae84d88d7398a13bd4b211487cdc024732666/ \
           --platform managed \
           --allow-unauthenticated \
           --memory 512M
