name: Push to GCR and Deploy GitHub Action
on:
  push
jobs:
  build-and-push-to-gcr-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
      
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: hidden-solstice-337107
          image_name: myimage
          image_tag: latest
          dockerfile: Dockerfile
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'hello-cloud-run'
          image: 'gcr.io/hidden-solstice-337107/myimage'
